---
- name: Install Java, JDK, and Jenkins
  hosts: web
  become: true
  tasks:
    - name: Update package lists
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: true
        autoclean: true

    - name: Install Java and JDK
      ansible.builtin.apt:
        name:
          - openjdk-17-jre
          - fontconfig
        state: present

    - name: Add Jenkins GPG key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        state: present
      register: jenkins_key

    - name: Add Jenkins apt repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/
        state: present

    - name: Update apt packages cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: true

    - name: Allow incoming traffic on port 8080
      community.general.ufw:
        rule: allow
        port: 8080

    - name: Allow OpenSSH (SSH)
      community.general.ufw:
        rule: allow
        port: OpenSSH

    - name: Enable UFW
      community.general.ufw:
        state: enabled
