---
- name: Setup Nginx on EC2
  hosts: web
  become: true

  tasks:
    - name: Start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Copy HTML file to serve
      ansible.builtin.copy:
        mode: '700'
        src: index.html
        dest: /var/www/html/index.html
